import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "@/common";
import { NavBar } from "@/common";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Netfix clone",
  description: "Generated by create next app",
};

export { metadata }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-netflix-color-dark text-white`}>
        <StoreProvider>
          <NavBar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
